# Generated by Django 2.0.7 on 2018-08-01 17:08

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=False)),
                ('recadastrado', models.BooleanField(default=False)),
                ('id_municipio', models.IntegerField(blank=True, null=True)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB ', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=3)),
                ('id_natureza_juridica', models.IntegerField(blank=True, null=True)),
                ('id_porte_empresa', models.IntegerField(blank=True, null=True)),
                ('id_ramo_negocio', models.IntegerField(blank=True, null=True)),
                ('id_cnae', models.IntegerField(blank=True, null=True)),
                ('id_unidade_cadastradora', models.IntegerField(blank=True, null=True)),
                ('habilitado_licitar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uasg',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('id_orgao', models.IntegerField(blank=True, null=True)),
                ('id_municipio', models.IntegerField(blank=True, null=True)),
                ('cep', models.CharField(max_length=20)),
                ('total_fornecedores_cadastrados', models.IntegerField(blank=True, null=True)),
                ('unidade_cadastradora', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='declaracao',
            name='id_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forn.Fornecedor'),
        ),
        migrations.AddField(
            model_name='declaracao',
            name='id_uasg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forn.Uasg'),
        ),
    ]
